version: "3.9"
services:
    postgres:
        container_name: pg
        image: postgres:15.1
        environment:
            POSTGRES_DB: "store"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            - .:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d store"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
        networks:
            - postgres

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:5.7
        environment:
            PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "test"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
